name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Check for conflicts
        id: conflicts
        run: |
          git fetch origin main:main
          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
          HAS_CONFLICTS=$(git merge-tree $(git merge-base main ${{ github.head_ref }}) main ${{ github.head_ref }} | grep "<<<<<<<" || true)
          if [[ -z "$HAS_CONFLICTS" ]]; then
            echo "No conflicts detected."
            echo "::set-output name=conflict::false"
          else
            echo "Conflicts detected!"
            echo "::set-output name=conflict::true"
          fi
      
      - name: Send message with Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} has made a PR on main: ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}
            Conflict Status: ${{ steps.conflicts.outputs.conflict == 'true' && 'Yes' || 'No' }}
